### ISSUE TITLE
列表快速滑动中，出现崩溃。

### ISSUE THREAD

**Issue by tzrgaga** [laucherish/PureZhihuD#2]
我的机器是Nexus5:

03-24 20:12:31.377 1227-7114/io.github.laucherish.purezhihud E/AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-58
                                                                               Process: io.github.laucherish.purezhihud, PID: 1227
                                                                               java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
                                                                                   at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
                                                                                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                   at java.lang.Thread.run(Thread.java:818)
                                                                                Caused by: rx.exceptions.OnErrorNotImplementedException
                                                                                   at rx.Observable$27.onError(Observable.java:7923)
                                                                                   at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:159)
                                                                                   at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
                                                                                   at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:191)
                                                                                   at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:162)
                                                                                   at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                   at java.lang.Thread.run(Thread.java:818) 
                                                                                Caused by: java.net.SocketTimeoutException
                                                                                   at java.net.PlainSocketImpl.read(PlainSocketImpl.java:484)
                                                                                   at java.net.PlainSocketImpl.-wrap0(PlainSocketImpl.java)
                                                                                   at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
                                                                                   at okio.Okio$2.read(Okio.java:139)
                                                                                   at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
                                                                                   at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
                                                                                   at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
                                                                                   at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
                                                                                   at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
                                                                                   at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125)
                                                                                   at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:723)
                                                                                   at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:81)
                                                                                   at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:708)
                                                                                   at com.facebook.stetho.okhttp3.StethoInterceptor.intercept(StethoInterceptor.java:59)
                                                                                   at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:681)
                                                                                   at io.github.laucherish.purezhihud.network.manager.RetrofitManager$1.intercept([RetrofitManager.java:97](https://github.com/laucherish/PureZhihuD/blob/master/app/src/main/java/io/github/laucherish/purezhihud/network/manager/RetrofitManager.java#L97))
                                                                                   at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:681)
                                                                                   at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:563)
                                                                                   at okhttp3.RealCall.getResponse(RealCall.java:241)
                                                                                   at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
                                                                                   at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:203)
                                                                                   at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
                                                                                   at io.github.laucherish.purezhihud.network.manager.RetrofitManager$1.intercept([RetrofitManager.java:97](https://github.com/laucherish/PureZhihuD/blob/master/app/src/main/java/io/github/laucherish/purezhihud/network/manager/RetrofitManager.java#L97))
                                                                                   at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
                                                                                   at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
                                                                                   at okhttp3.RealCall.execute(RealCall.java:57)
                                                                                   at retrofit2.OkHttpCall.execute(OkHttpCall.java:177)
                                                                                   at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:111)
                                                                                   at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:92)
                                                                                   at rx.Observable$2.call(Observable.java:162)
                                                                                   at rx.Observable$2.call(Observable.java:154)
                                                                                   at rx.Observable$2.call(Observable.java:162)
                                                                                   at rx.Observable$2.call(Observable.java:154)
                                                                                   at rx.Observable.unsafeSubscribe(Observable.java:8098)
                                                                                   at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
                                                                                   at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
                                                                                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                   at java.lang.Thread.run(Thread.java:818)

**Comment by laucherish** [comment]
谢谢提供log。

**Comment by shikuikui** [comment]
遇到同样的问题

**Comment by fewwind** [comment]
asset目录下不会写···能帮忙发一份吗
